[package]
name = "uefi-morpion"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4"
uefi = "0.18"
uefi-services = "0.15"
embedded-graphics = "0.7"
uefi-graphics = "0.4.0"